// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhpaxdfizwxkiogqtphn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlocGF4ZGZpend4a2lvZ3F0cGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTQxODQsImV4cCI6MjA1Nzk3MDE4NH0.y8hOHVMlfCYR80JjKnL99HuYqwaT5Jaib9m7_43RROY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);